### ISSUE TITLE
Export Database

### ISSUE THREAD

**Issue by GCPBigData** [hendisantika/spring-boot-excel-csv-pdf#1]
I'm trying to use your pŕ object, but I'm getting a bug ! i need you help !

Warning:(10, 57) java: org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter in org.springframework.web.servlet.config.annotation has been deprecated

**Comment by hendisantika** [comment]
Ooo.. Sorry for late response @DevJoseWeb. Is it already solved?

**Comment by hendisantika** [comment]
Because there is no response. I will close this issue.
